# Generated by Django 2.1 on 2018-08-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Type',
            new_name='type',
        ),
    ]
